### PR TITLE
Pin memcache to 2.0-alpha7 until Acquia cloud is ready.

### PR DESCRIPTION
**Pull request by japerry**
Fixes # 
--------
Currently, BLT 10.x builds will fail on Acquia cloud due to a memcache version mismatch. This is known and handled in 9.x, but 10.x is building 2.0 because its not pinned to alpha7.

Error:
```ArgumentCountError: Too few arguments to function Drupal\memcache\MemcacheBackend::__construct(), 3 passed in /mnt/www/html/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 101 and exactly 4 expected in Drupal\memcache\MemcacheBackend->__construct() (line 62 of /mnt/www/html/docroot/modules/contrib/memcache/src/MemcacheBackend.php). ```

Changes proposed:
---------
Pin to Alpha 7 until Cloud is working with 2.0 properly.

Steps to replicate the issue:
----------
1. Build a BLT site
2. Deploy to cloud
3. Error!

### CODE REVIEW

**Comment by lcatlett** [comment]
This is a critical PR, as updating memcache to any version newer than alpha7 will result in a WSOD or other errors. Since BLT 10.x is being used in Acquia's ORCA, this is currently blocking internal testing. See https://github.com/acquia/blt/pull/3259#issuecomment-443554214
