### ISSUE TITLE
php-tideways xhprof installation issue

### ISSUE THREAD

**Issue by rashid-alshaya** [acquia/blt#2426]
My system information:
* Operating system type: OSX
* Operating system version: high seirra 10.13.2
* BLT version: 2.15.2

When i run the following command
  blt vm
getting following error:

```
TASK [geerlingguy.php-tideways : Download and untar Tideways.] *****************
changed: [alshaya]

TASK [geerlingguy.php-tideways : Build Tideways.] ******************************
changed: [alshaya] => (item=phpize)
changed: [alshaya] => (item=./configure)
failed: [alshaya] (item=make) => {"changed": true, "cmd": "make", "delta": "0:00:00.094298", "end": "2018-01-09 06:13:12.967110", "item": "make", "msg": "non-zero return code", "rc": 2, "start": "2018-01-09 06:13:12.872812", "stderr": "In file included from /root/php5.6/php-profiler-extension-master/tideways_xhprof.c:9:0:\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:33:5: error: unknown type name 'zend_string'\n     zend_string *parent_class;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:34:5: error: unknown type name 'zend_string'\n     zend_string *parent_function;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:36:5: error: unknown type name 'zend_string'\n     zend_string *child_class;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:37:5: error: unknown type name 'zend_string'\n     zend_string *child_function;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:40:5: error: unknown type name 'zend_long'\n     zend_long count;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:41:5: error: unknown type name 'zend_long'\n     zend_long wall_time;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:42:5: error: unknown type name 'zend_long'\n     zend_long cpu_time;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:43:5: error: unknown type name 'zend_long'\n     zend_long memory;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:44:5: error: unknown type name 'zend_long'\n     zend_long memory_peak;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:54:5: error: unknown type name 'zend_string'\n     zend_string         *function_name;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:55:5: error: unknown type name 'zend_string'\n     zend_string         *class_name;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:71:5: error: unknown type name 'zend_string'\n     zend_string *root;\n     ^\n/root/php5.6/php-profiler-extension-master/php_tideways_xhprof.h:76:5: error: unknown type name 'zend_long'\n     zend_long flags;\n     ^\nIn file included from /root/php5.6/php-profiler-extension-master/tideways_xhprof.c:13:0:\n/root/php5.6/php-profiler-extension-master/tracing.h:15:146: error: unknown type name 'zend_long'\n xhprof_callgraph_bucket *tracing_callgraph_bucket_find(xhprof_callgraph_bucket *bucket, xhprof_frame_t *current_frame, xhprof_frame_t *previous, zend_long key);\n                                                                                                                                                  ^\n/root/php5.6/php-profiler-extension-master/tracing.h:17:20: error: unknown type name 'zend_long'\n void tracing_begin(zend_long flags TSRMLS_DC);\n                    ^\n/root/php5.6/php-profiler-extension-master/tracing.h: In function 'tracing_fast_free_frame':\n/root/php5.6/php-profiler-extension-master/tracing.h:24:46: error: 'tideways_xhprof' undeclared (first use in this function)\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:41:25: note: in expansion of macro 'TXRG'\n     p->previous_frame = TXRG(frame_free_list);\n                         ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:46: note: each undeclared identifier is reported only once for each function it appears in\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:41:25: note: in expansion of macro 'TXRG'\n     p->previous_frame = TXRG(frame_free_list);\n                         ^\n/root/php5.6/php-profiler-extension-master/tracing.h:41:30: error: 'frame_free_list' undeclared (first use in this function)\n     p->previous_frame = TXRG(frame_free_list);\n                              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h: In function 'tracing_fast_alloc_frame':\n/root/php5.6/php-profiler-extension-master/tracing.h:24:46: error: 'tideways_xhprof' undeclared (first use in this function)\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:49:9: note: in expansion of macro 'TXRG'\n     p = TXRG(frame_free_list);\n         ^\n/root/php5.6/php-profiler-extension-master/tracing.h:49:14: error: 'frame_free_list' undeclared (first use in this function)\n     p = TXRG(frame_free_list);\n              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h: At top level:\n/root/php5.6/php-profiler-extension-master/tracing.h:59:1: error: unknown type name 'zend_string'\n static zend_always_inline zend_string* tracing_get_class_name(zend_execute_data *data TSRMLS_DC)\n ^\n/root/php5.6/php-profiler-extension-master/tracing.h: In function 'tracing_get_class_name':\n/root/php5.6/php-profiler-extension-master/tracing.h:67:21: error: 'zend_execute_data' has no member named 'func'\n     curr_func = data->func;\n                     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:72:9: warning: return from incompatible pointer type [enabled by default]\n         return curr_func->common.scope->name;\n         ^\n/root/php5.6/php-profiler-extension-master/tracing.h: At top level:\n/root/php5.6/php-profiler-extension-master/tracing.h:78:1: error: unknown type name 'zend_string'\n static zend_always_inline zend_string* tracing_get_function_name(zend_execute_data *data TSRMLS_DC)\n ^\n/root/php5.6/php-profiler-extension-master/tracing.h: In function 'tracing_get_function_name':\n/root/php5.6/php-profiler-extension-master/tracing.h:86:21: error: 'zend_execute_data' has no member named 'func'\n     curr_func = data->func;\n                     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:97:5: warning: return from incompatible pointer type [enabled by default]\n     return curr_func->common.function_name;\n     ^\n/root/php5.6/php-profiler-extension-master/tracing.h: At top level:\n/root/php5.6/php-profiler-extension-master/tracing.h:100:61: error: unknown type name 'zend_string'\n zend_always_inline static int tracing_enter_frame_callgraph(zend_string *root_symbol, zend_execute_data *execute_data TSRMLS_DC)\n                                                             ^\n/root/php5.6/php-profiler-extension-master/tracing.h: In function 'tracing_exit_frame_callgraph':\n/root/php5.6/php-profiler-extension-master/tracing.h:24:46: error: 'tideways_xhprof' undeclared (first use in this function)\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:156:37: note: in expansion of macro 'TXRG'\n     xhprof_frame_t *current_frame = TXRG(callgraph_frames);\n                                     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:156:42: error: 'callgraph_frames' undeclared (first use in this function)\n     xhprof_frame_t *current_frame = TXRG(callgraph_frames);\n                                          ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h:158:5: error: unknown type name 'zend_long'\n     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;\n     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:158:49: error: 'clock_source' undeclared (first use in this function)\n     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;\n                                                 ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h:158:69: error: 'timebase_factor' undeclared (first use in this function)\n     zend_long duration = time_milliseconds(TXRG(clock_source), TXRG(timebase_factor)) - current_frame->wt_start;\n                                                                     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h:162:44: error: 'callgraph_buckets' undeclared (first use in this function)\n     xhprof_callgraph_bucket *bucket = TXRG(callgraph_buckets)[slot];\n                                            ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h:164:12: warning: assignment makes pointer from integer without a cast [enabled by default]\n     bucket = tracing_callgraph_bucket_find(bucket, current_frame, previous, key);\n            ^\n/root/php5.6/php-profiler-extension-master/tracing.h:169:103: warning: pointer/integer type mismatch in conditional expression [enabled by default]\n         bucket->child_class = current_frame->class_name ? zend_string_copy(current_frame->class_name) : NULL;\n                                                                                                       ^\n/root/php5.6/php-profiler-extension-master/tracing.h:170:32: warning: assignment makes pointer from integer without a cast [enabled by default]\n         bucket->child_function = zend_string_copy(current_frame->function_name);\n                                ^\n/root/php5.6/php-profiler-extension-master/tracing.h:173:119: warning: pointer/integer type mismatch in conditional expression [enabled by default]\n             bucket->parent_class = previous->class_name ? zend_string_copy(current_frame->previous_frame->class_name) : NULL;\n                                                                                                                       ^\n/root/php5.6/php-profiler-extension-master/tracing.h:174:37: warning: assignment makes pointer from integer without a cast [enabled by default]\n             bucket->parent_function = zend_string_copy(previous->function_name);\n                                     ^\n/root/php5.6/php-profiler-extension-master/tracing.h:196:14: error: 'flags' undeclared (first use in this function)\n     if (TXRG(flags) & TIDEWAYS_XHPROF_FLAGS_CPU) {\n              ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tracing.h:208:10: error: 'function_hash_counters' undeclared (first use in this function)\n     TXRG(function_hash_counters)[current_frame->hash_code]--;\n          ^\n/root/php5.6/php-profiler-extension-master/tracing.h:24:63: note: in definition of macro 'TXRG'\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                                               ^\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c: In function 'zif_tideways_xhprof_enable':\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c:26:5: error: unknown type name 'zend_long'\n     zend_long flags = 0;\n     ^\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c: In function 'zm_startup_tideways_xhprof':\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c:65:28: warning: assignment from incompatible pointer type [enabled by default]\n     _zend_execute_internal = zend_execute_internal;\n                            ^\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c:66:27: warning: assignment from incompatible pointer type [enabled by default]\n     zend_execute_internal = tideways_xhprof_execute_internal;\n                           ^\nIn file included from /root/php5.6/php-profiler-extension-master/tideways_xhprof.c:13:0:\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c: In function 'zm_deactivate_tideways_xhprof':\n/root/php5.6/php-profiler-extension-master/tracing.h:24:46: error: 'tideways_xhprof' undeclared (first use in this function)\n #define TXRG(v) ZEND_MODULE_GLOBALS_ACCESSOR(tideways_xhprof, v)\n                                              ^\n/root/php5.6/php-profiler-extension-master/tideways_xhprof.c:95:18: note: in expansion of macro 'TXRG'\n         bucket = TXRG(callgraph_buckets)[i];\n                  ^\n/root/php5.6/php-profiler-extension`
```

**Comment by Sanjib-Dutta** [comment]
I am facing the same issue

**Comment by grasmash** [comment]
I don't believe that tideways is part of BLT's default Drupal VM configuration. Regardless, this issue does not appear to be related to BLT.

Please file this issue in the Drupal VM issue queue: https://github.com/geerlingguy/drupal-vm/issues.

**Comment by grasmash** [comment]
I'm going to give @geerlingguy a chance to comment before closing.

**Comment by geerlingguy** [comment]
I would file the issue in the geerlingguy.php-tideways repository.

Note that depending on upstream support, Tideways may or may not work on PHP 5.6 anymore. I haven’t personally tested it with PHP < 7.0 in the past year.
